package de.turnertech.ows.filter;

public enum BinaryComparisonName {
    PROPERTY_IS_EQUAL_TO,
    PROPERTY_IS_NOT_EQUAL_TO,
    PROPERTY_IS_LESS_THAN,
    PROPERTY_IS_GREATER_THAN,
    PROPERTY_IS_LESS_THAN_OR_EQUAL_TO,
    PROPERTY_IS_GREATER_THAN_OR_EQUAL_TO;
}
