openapi: 3.0.3
info:
  title: The BOSCOP API
  description: |-
    The BOSCOP service collects and displays an overview of German BOS relevant mission information. It accepts GPS position input and allows for the creation and modification of information.
  termsOfService: https://cop.turnertech.de/terms/
  contact:
    email: turnertech@outlook.de
  license:
    name: Commercial License
    url: http://todo
  version: 1.0.11
servers:
  - url: https://cop.turnertech.de
tags:
  - name: COP
    description: Access to the Common Operational Picture
    externalDocs:
      description: What is a COP?
      url: https://en.wikipedia.org/wiki/Common_operational_picture
  - name: tracker
    description: The GPS tracker API
security:
  - digest: []
paths:
  /cop:
    get:
      tags:
        - COP
      summary: Get the COP
      description: Gets the COP as a GeoJSON
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/COP'
  /tracker:
    get:
      tags:
        - tracker
      summary: List the known Trackers
      description: Lists the known GPS trackers as JSON. Note that this interface will only return trackers for which you are authorised!
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackerList'
    post:
      tags:
        - tracker
      summary: Create or Update a Tracker
      description: For simplicity, the creation and updating of trackers uses the same interface. The OPTA is the unique ID.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tracker'
      responses:
        '200':
          description: Successful operation
        '400':
          description: User failure in request
          content:
            text/plain:
              schema:
                type: string
                example: Error Description

  /tracker/update:
    put:
      tags:
        - tracker
      summary: Update a Tracker 
      description: This is a limited version of the /tracker API and is intended for use by devices such as GPS Trackers in vehicles. This endpoint uses an API Key which is only valid for exactly one OPTA, so if a physical tracker is compromised, the damage is limited to one OPTA.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Tracker'
      responses:
        '200':
          description: Successful operation
        '400':
          description: User failure in request
          content:
            text/plain:
              schema:
                type: string
                example: Error Description
        '401':
          description: Unauthorised
      security:
        - apiKey:
          - user
        
components:
  schemas:
    COP:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          example: FeatureCollection
        features:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                example: Feature
              geometry:
                type: object
                properties:
                  type:
                    type: string
                    example: Point
                  coordinates:
                    type: array
                    items:
                      type: number
                      example: [23.123, 32.254]
              properties:
                type: object
                properties:
                  OPTA:
                    type: string
                    example: BUTHWL  OBNA 2110
    Tracker:
      type: object
      required:
        - opta
        - lon
        - lat
      properties:
        opta:
          type: string
          example: BUTHWL  OBNA 2110
        status:
          type: integer
          example: 1
        lon:
          type: number
          example: 43.32
        lat:
          type: number
          example: 23.32
    TrackerList:
      type: object
      required:
        - trackers
      properties:
        trackers:
          type: array
          items:
            $ref: '#/components/schemas/Tracker'
  securitySchemes:
    digest:
      type: http
      scheme: basic
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key